import type { Metadata } from "next";

import { Toaster } from "react-hot-toast";
import "./globals.css";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";

export const metadata: Metadata = {
  title: "Vercel Jobs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <Header />
        <Toaster position="top-right" reverseOrder={false} />
        <div className="pt-16">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
